### ISSUE TITLE
Meerdere net frequenties mogelijk maken

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Netkaart-scripts#13]
_From @BaDu-HSN on October 27, 2016 10:32_

Dus naast AC en DC ook "AC 16,6Hz" toestaan en evt "AC 60Hz".
AC staat dan standaard voor 50Hz

Aangepast moeten worden de database tabel, de balloonscripts en het importscript.

_Copied from original issue: Hoogspanningsnet/GE-scripts#6_

**Comment by HansNien** [comment]
Is aanwezig in versie 7, via pulldown.
