### ISSUE TITLE
Blackman-afbeeldingen schrappen in versie 7 en vervangen door tekstje

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Netkaart-scripts#21]
_From @HansNien on November 15, 2017 22:12_

Zoals benoemd in de appgroep. Van de meeste objecten zoals buitenlandse grondkabels krijgen we nooit een foto en dat moet ook geen doel zijn, maar wel nemen de blackmans kostbare ruimte in die we met name op telefoonschermen wel beter kunnen gebruiken.

Wie het was weet ik niet meer, maar wel werd het argument geopperd dat de blackmans aanzetten tot het insturen van foto's om dat erdoor te zien is dat er eentje gewild is. Dat effect verdwijnt als we de blackmans helemaal schrappen, maar we kunnen een elegante middenweg bereiken door de afbeelding (een grote PNG) te vervangen door een geschreven regel tekst tussen vierkante haken: [geen foto beschikbaar]. Die neemt weinig ruimte in, maar vertelt precies hetzelfde.

_Copied from original issue: Hoogspanningsnet/Webkaart-scripts#185_

**Comment by BaDu-HSN** [comment]
_From @Knarvel on November 16, 2017 13:0_

Dat was ik. Mijn idee was om in de blackman aktief naar fotoos te vragen, met ook een url naar een upload-pagina. Maar dat kan met een stukje text natuurlijk net zo goed gedaan worden.

**Comment by BaDu-HSN** [comment]
_From @HansNien on November 24, 2017 15:13_

Mensen actief aanmoedigen tot het insturen van foto's, daar ben ik op mijn beurt een beetje huiverig voor. Het kan enorm uit de hand lopen qua aantal en qua werk dat we eraan gaan hebben (iedere foto moet gehost, gelinkt en gecontroleerd worden). We verliezen er ook een belangrijk deel van de controle mee op de bron van herkomst. Voordat er een aanmoedigingsbeleid komt denk ik dat we eerst eens een goede discussie hierover moeten hebben.

**Comment by BaDu-HSN** [comment]
Wat doen we er voor versie 7 mee?

**Comment by HansNien** [comment]
Inmiddels lijkt het verwerkt. Afgeschaft, tenzij het het exemplaar van FOUT: geen data betreft. Die heeft nog wel wat.
