### ISSUE TITLE
Veld Type (stationstype) wordt niet onthouden of weergegeven

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Netkaart-scripts#27]
_From @HansNien on September 24, 2017 20:3_

Het veld Type bij de categorie Hoogspanningsstation bevat een pulldownmenu waarin kan worden gekozen uit een discreet aantal opties. Nog niet aangeraakt is het veld leeg in versie 6.0 (er kan in V7.0 een default in, maar dat is een ander ding), maar eenmaal aangeraakt staat er bijvoorbeeld Trafostation, Converter of Klantstation. Echter, dit lijkt niet goed bewaard te blijven. Voor het Nederlandse 110 kV-gebied heb ik ooit alle stations eens van de correcte aanduiding voorzien, maar dat verdween na enige tijd vanzelf weer zodat het veld opnieuw leeg (alsof nooit aangeraakt) werd weergegeven. Een paar weken terug heb ik voor een stuk of tien stations rond de Drents-Overijsselse grens opnieuw alle types correct ingesteld en na een week of twee is de netkaart ze nu opnieuw allemaal vergeten. Dat lijkt op wat er de eerste keer ook gebeurde. Er zit dus een vreemde bug in dit veld.

_Copied from original issue: Hoogspanningsnet/Webkaart-scripts#179_

**Comment by BaDu-HSN** [comment]
_From @HansNien on November 25, 2017 8:29_

Dank voor het noteren als milestone. Een korte blik op de zaak toont dat deze bug nog steeds bestaat. Als kanarie in de kolenmijn gebruik ik al enige tijd station Veenoord, waar telkens Type wordt ingevuld. Aan de log is te zien dat deze schijnbaar elke paar weken zijn type-informatie is verloren. Geen dagelijks gebeuren, maar kennelijk om de paar weken. Totaal niet logisch. Geen idee wat die bug veroorzaakt.

**Comment by HansNien** [comment]
Update op deze: hij is er nog altijd en voor het eerst is hij me nu ook opgevallen bij stations in het buitenland. Ook de converterplatforms in de Noordzee onthouden hun status niet.

**Comment by BaDu-HSN** [comment]
hmmm een echte bug dus. Investigating

**Comment by BaDu-HSN** [comment]
Gevonden en opgelost:
Bij een import van een wijziging via de beheerinterface (uploaden van een nieuwe KML), werdt het subtype veld op een lege string gezet.
