### ISSUE TITLE
Beheer - Land bepalen op basis van IP

### ISSUE THREAD

**Issue by BaDu-HSN** [Hoogspanningsnet/Netkaart-scripts#65]
In de view logging loggen we het land van de bezoeker, dit werkt op dit moment niet door een te groot aantal queries naar de betreffende service. Nieuwe service gebruiken of eigen iets maken.

**Comment by HansNien** [comment]
Betreft dit eventueel ook de openingshoek en extend van de netkaart wanneer een gebruiker deze opvraagt, of zit ik hier nu verkeerd te denken?

**Comment by BaDu-HSN** [comment]
Nee dit is alleen het openen van de kaart (de buitenschil in GE en de index.php in de webkaart).

**Comment by BaDu-HSN** [comment]
Opgelost we maken nu gebruik van de service van http://freegeoip.net
(maximaal 15000 queries per uur, dat gaan we makkelijk redden)
