### ISSUE TITLE
Toevoegen tekst 'achtergrondkaart' naast font-awesome icoontje in sidebarmenu

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Netkaart-scripts#82]
We hebben wel eens vragen binnengekregen van mensen die spanningsloze objecten zo slecht zichtbaar vinden op Esri Light als defaultondergrond. Daaruit blijkt dat ze niet weten dat je een andere achtergrondkaart kan kiezen. Een oplossing daarvoor is in het instellingenmenu bij de keuze van achtergrondkaarten naast het icoontje (font-awesome) ook een tekst weer te geven, zoals 'achtergrondkaart' of 'kies achtergrond' of iets soortgelijks. 
Ik heb eens gekeken in de testnetkaart of dat kan, maar ik kom er zelf niet uit. Daarom zet ik hem op de wishlist voor V7.

**Comment by BaDu-HSN** [comment]
Het blijkt erg lastig een tekst weer te geven naast het icoon.
Het zou misschien kunnen met een hoop gefrunnik in de code, wat wellicht makkelijker is :
Gewoon het lijstje met layers standaard expanded weergeven
Dit maakt de sidebar wel langer maar een scrollbar geeft aan dat de boel verder doorloopt.
![afbeelding](https://user-images.githubusercontent.com/21307438/50396946-5c20e480-076d-11e9-8b73-e8dd6ed2ff23.png)
