### ISSUE TITLE
Functie Download de volledige netkaart werkt niet goed

### ISSUE THREAD

**Issue by HansNien** [Hoogspanningsnet/Netkaart-scripts#85]
Bij het downloaden via het ACP van de volledige netkaart wordt geen enorme KML maar slechts een kopie van de wrapper binnengehaald, die nog niet eens 1 kB is. Ergens gaat er dus wat mis.

**Comment by BaDu-HSN** [comment]
Dit wordt veroorzaakt doordat je probeert de beheeromgeving te benaderen als http (ipv https).
De juiste link is https://netkaart.hoogspanningsnet.com/beheer/beheer.php
